[package]
name = "sumup"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "SumUp API"

[dependencies]
serde_json = "1.0"
thiserror = "1.0"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.ureq]
version = "2.5"
features = ["json"]
